- server/booking-router.go
With this new Feature you can use API endpoint /bookings/ to create bookings for other users, even if they do not (yet) exists.
For example to reserve spaces for the on-site onboarding newbies.
Role roleSpaceAdmin or roleOrgAdmin required.
example:
POST to /booking/
```json
{
"enter":  "2022-03-10T00:00:00.000Z",
"leave":  "2022-03-10T23:59:59.000Z", 
"spaceId":  "b9f1a338-02f7-46d4-9056-da4af7a057ad", 
"UserEmail":  "newemployee@company.com" 
} 
```
> Admin create bookings for other users, even for users not created yet

- .gitignore
- booking-ui/src/App.css
- booking-ui/src/i18n.ts
- booking-ui/src/pages/Search.tsx
- build.sh
- server/space-repository.go
- server/space-router.go
* Show Own Booked desks (Color violet)
* Show who has booked for spaceadmins (even if disabled)
* Tooltips who as booked
* OK Button after booking (with reload)
> Some features: show booked desks in other color, spaceadmin access to bookers' names, tooltips

- booking-ui/src/pages/Search.tsx
- server/space-repository.go
- server/space-router.go
This PR implements minor improvements for PR #28
> Minor improvements to PR #28

- admin-ui/src/components/NavBar.tsx
- admin-ui/src/components/SideBar.tsx
- admin-ui/src/i18n.ts
- admin-ui/src/pages/EditAuthProvider.tsx
- admin-ui/src/pages/LoginSuccess.tsx
- booking-ui/src/components/NavBar.tsx
- booking-ui/src/i18n.ts
* Bugfix OpenID-SpaceAdminLogin
* Links between Admin- and Booking-UI
* added Keycloak Auth-Template
> Login Enhancements and Fixes

- admin-ui/src/components/SideBar.tsx
- admin-ui/src/i18n.ts
- booking-ui/src/components/NavBar.tsx
Small UI improvements for PR #35
> Navbar fixes

- booking-ui/public/index.html
- booking-ui/src/App.css
- booking-ui/src/components/Loading.tsx
- booking-ui/src/pages/Login.css
- booking-ui/src/pages/Login.tsx
> Pwa improvements

- admin-ui/src/pages/EditLocation.tsx
after react upgrade only the last space was loaded into EditLocations, causing also #48 
This fixes that Bug
> onlyLastSpace Fix-Issue-48

- booking-ui/src/pages/search.tsx
> fix-datepicker bug for #143

- admin-ui/public/locales/de/admin.json
- admin-ui/public/locales/en/admin.json
- admin-ui/public/locales/fr/admin.json
- admin-ui/public/locales/it/admin.json
- admin-ui/src/pages/settings/index.tsx
- booking-ui/public/locales/de/common.json
- booking-ui/public/locales/en/common.json
- booking-ui/public/locales/fr/common.json
- booking-ui/public/locales/it/common.json
- booking-ui/src/components/RuntimeConfig.ts
- booking-ui/src/types/ErrorText.ts
- server/booking-repository.go
- server/booking-router.go
- server/booking-router_test.go
- server/routes.go
- server/settings-repository.go
- server/settings-router.go
- server/settings-router_test.go
To avoid users booking more than n overlapping locations adding a setting to add a user booking concurrency limit.
Defaults to no limit, as before
Translations won't be great (google translate) let me know if changes desired
> Add user concurrency limit setting

- booking-ui/package-lock.json
- booking-ui/package.json
- booking-ui/public/locales/de/common.json
- booking-ui/public/locales/en/common.json
- booking-ui/public/locales/fr/common.json
- booking-ui/public/locales/it/common.json
- booking-ui/public/locales/nl/common.json
- booking-ui/src/pages/buddies.tsx
- booking-ui/src/pages/search.tsx
- booking-ui/src/styles/Login.css
- commons/ts/src/types/Buddy.ts
- commons/ts/src/types/User.ts
- server/booking-repository.go
- server/buddy-router.go
- server/user-router.go
Adds the following functionality:
- Tooltip hover over desks to see who is sitting there.
- See each buddy's next earliest booking
- Add buddy by Email
- Some formatting
> Add various functionalities to SeatSurfing

- booking-ui/package-lock.json
- booking-ui/src/pages/search.tsx
- commons/ts/package-lock.json
- commons/ts/package.json
- commons/ts/src/util/Formatting.ts
PR #254 introduced a slider to get a quick overview of space availability during the upcoming days. However, from my point of view, the handling was not optimal. This PR improved the new feature.
> Fix slider introduced with pr #254

- admin-ui/next-i18next.config.js
- admin-ui/src/pages/login/index.tsx
- admin-ui/src/styles/Login.css
- booking-ui/next-i18next.config.js
- booking-ui/src/pages/login/index.tsx
- booking-ui/src/styles/Login.css
Adds language selectors to login screens of booking and admin ui (issue #2 )
> Added ability to change language manually (issue #2)

- server/booking-repository.go
- server/booking-router_test.go
When 
* the enter time of a booking matches another booking's leave time or
* the leave time of a booking matched another booking's enter time
the a conflict was detected until now.
PR #292 relaxed these check as an option. However, I think that this is unwanted behaviour. Therefore, this PR generally relaxes the conflict checking.
> Relaxed conflict checking

- booking-ui/public/locales/de/common.json
- booking-ui/public/locales/en/common.json
- booking-ui/src/pages/search.tsx
- commons/ts/src/types/SearchAttribute.ts
- commons/ts/src/types/SpaceAttribute.ts
- server/location-router.go
- server/location-router_test.go
- server/space-repository.go
- server/space-repository_test.go
This PR adds additional filtering options to the Booking UI (as requested in issue #294).
* Number of spaces
* Number of free spaces
* Buddies on site
> feat: add additional filtering options

- admin-ui/public/locales/de/admin.json
- admin-ui/public/locales/en/admin.json
- admin-ui/public/locales/fr/admin.json
- admin-ui/public/locales/he/admin.json
- admin-ui/public/locales/it/admin.json
- admin-ui/public/locales/nl/admin.json
- admin-ui/src/pages/bookings/[id].tsx
- booking-ui/public/locales/de/common.json
- booking-ui/public/locales/en/common.json
- booking-ui/public/locales/fr/common.json
- booking-ui/public/locales/he/common.json
- booking-ui/public/locales/hu/common.json
- booking-ui/public/locales/it/common.json
- booking-ui/public/locales/nl/common.json
- booking-ui/public/locales/ro/common.json
- booking-ui/src/pages/search.tsx
- commons/ts/src/util/Formatting.ts
> fix: inconsistent date format

- booking-ui/src/pages/search.tsx
> feat: allow cancel booking from map

- server/router/booking-router.go
- server/util/timezones.go
> fix: list user bookings according to location's timezone

- server/config/config.go
- server/res/email-resetpw_de.txt
- server/res/email-resetpw_en.txt
- server/router/auth-router.go
- server/util/sendmail-acs.go
- server/util/sendmail.go
> feat: add Azure Communication Services (ACS) as alternative to SMTP for sending mails

- admin-ui/src/pages/settings/auth-providers/[id].tsx
> fix: add auth provider template for Okta

- admin-ui/src/pages/locations/[id].tsx
- commons/ts/src/types/Space.ts
- commons/ts/src/types/SpaceAttributeValue.ts
- server/repository/location-repository.go
- server/repository/space-attribute-value-repository.go
- server/repository/space-repository.go
- server/router/search-router.go
- server/router/space-router.go
> feat: add ability to assign attributes to spaces in Admin UI

- admin-ui/src/pages/login/index.tsx
- booking-ui/src/pages/login/index.tsx
> fix: make language changes persistent

- server/router/space-router.go
- server/router/test/space-router_test.go
Replaces PR #913 in combination with PR #923
> feat: endpoint for querying a single space's availability

- server/config/config.go
- server/util/domain-verification.go
- server/util/netutil.go
- server/util/test/domain-verification_test.go
- server/util/test/netutil_test.go
> feat: use custom DNS resolver in domain accessibility verification http client

- server/router/booking-router.go
This fixes the bug reported in #1214.
> fix: fix calculation for min. booking hours
